title: SORACOM Napter・AWS IoT Core・SORACOM Beamで学ぶMQTTハンズオン
description: Raspberry Pi、UD-LT2、SORACOM Napter、AWS IoT Core、SORACOM BeamでMQTTを学ぶ3時間ハンズオン
lang: ja
url: https://takao2704.github.io
baseurl: /aws-iot-soracom-mqtt-handson
repository: takao2704/aws-iot-soracom-mqtt-handson
github_url: https://github.com/takao2704/aws-iot-soracom-mqtt-handson
google_doc_url: https://docs.google.com/document/d/1ycGqSe2jDhFnPSkvkeJXDKymL5jKGqCOckqQiJXVIZc/edit
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - bridge
  - qa
  - .design
  - README.md
  - Gemfile
  - Gemfile.lock

